PcConfigurator/Entities/Memory.cs
using System.ComponentModel.DataAnnotations;

namespace PcConfigurator.Entities
{
    public class Memory : PowerConsumerComponent
    {
        [Required]
        public int TotalCapacity { get; set; }
        [Required]
        public int Count { get; set; }
        [Required]
        public string MemoryInterface { get; set; }
    }
}

PcConfigurator/Entities/Mongo/Memory.cs
using MongoDB.Bson.Serialization.Attributes;

namespace PcConfigurator.Entities.Mongo
{
    public class Memory : MongoEntity
    {
        [BsonElement("brand")]
        [BsonRequired]
        public string Brand { get; set; }

        [BsonElement("model")]
        [BsonRequired]
        public string Model { get; set; }

        [BsonElement("capacity")]
        [BsonRequired]
        public string Capacity { get; set; }

        [BsonElement("cl")]
        public string CasLatency { get; set; }

        [BsonElement("voltage")]
        public string Voltage { get; set; }

        [BsonElement("type")]
        [BsonRequired]
        public string Type { get; set; }

        [BsonElement("speed")]
        [BsonRequired]
        public string Speed { get; set; }

        [BsonElement("features")]
        public string Features { get; set; }
    }
}

PcConfigurator/Controllers/MemoryController.cs
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Newtonsoft.Json;
using PcConfigurator.Entities;
using PcConfigurator.Models.HomeModels;
using PcConfigurator.Service;

namespace PcConfigurator.Controllers
{
    public class MemoryController : Controller
    {
        private readonly IMemoryService _memoryService;

        public MemoryController(IMemoryService memoryService)
        {
            _memoryService = memoryService;
        }


        [HttpPost]
        public ActionResult LoadMemoryBrand(ConfigurationFormModel model)
        {
            var output = _memoryService.GetMemoryBrandsByCapacity(model.MemoryCapacity).Select(c => new { text = c, value = c });
            return Json(output);

        }

        [HttpPost]
        public ActionResult LoadMemoryId(ConfigurationFormModel model)
        {
            var output = _memoryService.GetMemoriesByCapacityAndBrand(model.MemoryCapacity, model.MemoryBrand).Select(m => new { text = m.Name, value = m.Id });
            return Json(output);
        }

        [HttpPost]
        public ActionResult LoadMemory(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return PartialView("_Memory", _memoryService.GetById(id));
        }

        //index,details,edit,delete,create

        [HttpGet]
        public ActionResult Index()
        {
            return View(_memoryService.GetAll());
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_memoryService.GetById(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Memory());
        }

        [HttpPost]
        public ActionResult Create(Memory memory)
        {
            if (ModelState.IsValid)
            {
                _memoryService.Insert(memory);
                return RedirectToAction("Index");
            }
            return View(memory);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _memoryService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_memoryService.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Memory memory)
        {
            if (ModelState.IsValid)
            {
                _memoryService.Update(memory);
                return RedirectToAction("Index");
            }
            return View(memory);
        }

    }
}

PcConfigurator/Views/Memory/Create.cshtml
@model PcConfigurator.Entities.Memory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Memory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemoryInterface, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemoryInterface, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemoryInterface, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PowerConsumption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PowerConsumption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PowerConsumption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Memory/Details.cshtml
@model PcConfigurator.Entities.Memory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Memory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemoryInterface)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemoryInterface)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PowerConsumption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PowerConsumption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalCapacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PcConfigurator/Views/Memory/Edit.cshtml
@model PcConfigurator.Entities.Memory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Memory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemoryInterface, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemoryInterface, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemoryInterface, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PowerConsumption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PowerConsumption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PowerConsumption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Memory/Index.cshtml
@model IEnumerable<PcConfigurator.Entities.Memory>

@{
    ViewBag.Title = "Memories";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Memory</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MemoryInterface)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PowerConsumption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalCapacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MemoryInterface)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PowerConsumption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalCapacity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

PcConfigurator/Views/Memory/_DropdownListGroup.cshtml
@model PcConfigurator.Models.HomeModels.ConfigurationFormModel
@{
    IList<SelectListItem> memoryCapacitySelectItems = Enumerable.Empty<SelectListItem>() as IList<SelectListItem>;
    if (Model.CpuBrandList != null)
    {
        memoryCapacitySelectItems = Model.MemoryCapacityList
            .Select(s => new SelectListItem { Text = s + " GB", Value = s.ToString() })
            .ToList();
    }
}


<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("MemoryCapacity", memoryCapacitySelectItems, "Capacity", new {@class = "form-control", @data_url = @Url.Action("LoadMemoryBrand", "Memory")})
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("MemoryBrand", Enumerable.Empty<SelectListItem>(), "Brand", new {@class = "form-control", @data_url = @Url.Action("LoadMemoryId", "Memory"), @style = "display:none;"})
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("MemoryId", Enumerable.Empty<SelectListItem>(), "Model", new {@class = "form-control", @data_url = @Url.Action("LoadMemory", "Memory"), @style = "display:none;"})
            </div>
        </div>
    </div>
</div>
<div id="MemoryView"></div>

PcConfigurator/Views/Memory/_Memory.cshtml
@model PcConfigurator.Entities.Memory
<hr />
<div class="row vcenter">
    <div class="col-xs-10 col-md-5">
        <div class="panel panel-success">
            <div class="panel-heading">@this.Model.Brand @this.Model.Name @Html.Raw(this.Model.Count + "x" + (this.Model.TotalCapacity/this.Model.Count))GB</div>
            @Html.HiddenFor(c => c.PowerConsumption)
            <table class="table table-hover">
                <tr>
                    <td>@Html.DisplayNameFor(model => model.TotalCapacity)</td>
                    <td>@Html.DisplayFor(model => model.TotalCapacity)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.MemoryInterface)</td>
                    <td>@Html.DisplayFor(model => model.MemoryInterface)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Count)</td>
                    <td>@Html.DisplayFor(model => model.Count)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.PowerConsumption)</td>
                    <td>@Html.DisplayFor(model => model.PowerConsumption)</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-xs-2 col-md-1">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    </div>
</div>