PcConfigurator/Controllers/StorageController.cs
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Newtonsoft.Json;
using PcConfigurator.Entities;
using PcConfigurator.Models.HomeModels;
using PcConfigurator.Service;

namespace PcConfigurator.Controllers
{
    public class StorageController : Controller
    {
        private readonly IStorageService _storageService;

        public StorageController(IStorageService storageService)
        {
            _storageService = storageService;
        }

        [HttpPost]
        public ActionResult LoadStorageBrand(ConfigurationFormModel model)
        {
            var output =
                _storageService.GetStorageBrandsByCapacity(model.StorageCapacity).Select(s => new { text = s, value = s });
            return Json(output);

        }

        [HttpPost]
        public ActionResult LoadStorageId(ConfigurationFormModel model)
        {
            var output =
                _storageService.GetStoragesByCapacityAndBrand(model.StorageCapacity, model.StorageBrand).Select(s => new { text = s.Name, value = s.Id });
            return Json(output);
        }

        [HttpPost]
        public ActionResult LoadStorage(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return PartialView("_Storage", _storageService.GetById(id));
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_storageService.GetAll());
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_storageService.GetById(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Harddrive());
        }

        [HttpPost]
        public ActionResult Create(Harddrive component)
        {
            if (ModelState.IsValid)
            {
                _storageService.Insert(component);
                return RedirectToAction("Index");
            }
            return View(component);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _storageService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_storageService.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Harddrive component)
        {
            if (ModelState.IsValid)
            {
                _storageService.Update(component);
                return RedirectToAction("Index");
            }
            return View(component);
        }
    }
}

PcConfigurator/Views/Storage/Create.cshtml
@model PcConfigurator.Entities.Harddrive

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Harddrive</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PowerConsumption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PowerConsumption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PowerConsumption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Interface, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Interface, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Interface, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Storage/Details.cshtml
@model PcConfigurator.Entities.Harddrive

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Harddrive</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PowerConsumption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PowerConsumption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interface)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interface)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PcConfigurator/Views/Storage/Edit.cshtml
@model PcConfigurator.Entities.Harddrive

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Harddrive</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PowerConsumption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PowerConsumption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PowerConsumption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Interface, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Interface, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Interface, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Storage/Index.cshtml
@model IEnumerable<PcConfigurator.Entities.Harddrive>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Storage</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PowerConsumption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Interface)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capacity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PowerConsumption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Interface)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capacity)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

PcConfigurator/Views/Storage/_DropdownListGroup.cshtml
@model PcConfigurator.Models.HomeModels.ConfigurationFormModel
@{
    IList<SelectListItem> storageCapacitySelectItems = Enumerable.Empty<SelectListItem>() as IList<SelectListItem>;
    if (Model.CpuBrandList != null)
    {
        storageCapacitySelectItems = Model.StorageCapacityList
            .Select(s => new SelectListItem { Text = s + " GB", Value = s.ToString() })
            .ToList();
    }
}

<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("StorageCapacity", storageCapacitySelectItems, "Capacity", new { @class = "form-control", @data_url = @Url.Action("LoadStorageBrand", "Storage") })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("StorageBrand", Enumerable.Empty<SelectListItem>(), "Brand", new { @class = "form-control", @data_url = @Url.Action("LoadStorageId", "Storage"), @style = "display:none;" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("StorageId", Enumerable.Empty<SelectListItem>(), "Model", new { @class = "form-control", @data_url = @Url.Action("LoadStorage", "Storage"), @style = "display:none;" })
            </div>
        </div>
    </div>
</div>
<div id="StorageView"></div>

PcConfigurator/Views/Storage/_Storage.cshtml
@model PcConfigurator.Entities.Harddrive
<hr />
<div class="row vcenter">
    <div class="col-xs-10 col-md-5">
        <div class="panel panel-success">
            <div class="panel-heading">@this.Model.Brand @this.Model.Name @this.Model.Capacity GB</div>
            @Html.HiddenFor(c => c.PowerConsumption)
            <table class="table table-hover">
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Capacity)</td>
                    <td>@Html.DisplayFor(model => model.Capacity)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Interface)</td>
                    <td>@Html.DisplayFor(model => model.Interface)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.PowerConsumption)</td>
                    <td>@Html.DisplayFor(model => model.PowerConsumption)</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-xs-2 col-md-1">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    </div>
</div>