PcConfigurator/Entities/Case.cs
using System;
using System.Collections.Generic;

namespace PcConfigurator.Entities
{
    public class Case : Component
    {
        public List<String> MotherboardCompatibility { get; set; }
    }
}

PcConfigurator/Entities/Mongo/Case.cs
using System;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;

namespace PcConfigurator.Entities.Mongo
{
    public class Case : MongoEntity
    {
        [BsonElement("brand")]
        [BsonRequired]
        public string Brand { get; set; }

        [BsonElement("model")]
        [BsonRequired]
        public string Model { get; set; }

        [BsonElement("type")]
        [BsonRequired]
        public string Type { get; set; }

        [BsonElement("mbCompatibility")]
        [BsonRequired]
        public List<String> MotherBoardCompatibility { get; set; }

        [BsonElement("features")]
        public string Features { get; set; }
    }
}

PcConfigurator/Controllers/CaseController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.Practices.ObjectBuilder2;
using Newtonsoft.Json;
using PcConfigurator.Entities;
using PcConfigurator.Models.HomeModels;
using PcConfigurator.Service;

namespace PcConfigurator.Controllers
{
    public class CaseController : Controller
    {
        private readonly ICaseService _caseService;

        public CaseController(ICaseService caseService)
        {
            _caseService = caseService;
        }
        [HttpPost]
        public ActionResult LoadCaseId(ConfigurationFormModel model)
        {
            var output = _caseService.GetCasesByConfiguration(model).Select(c => new { text = c.Name, value = c.Id });
            return Json(output);
        }

        [HttpPost]
        public ActionResult LoadCaseBrand(ConfigurationFormModel model)
        {
            var output = _caseService.GetCaseBrandsByFormat(model.MotherboardFormat).Select(b => new { text = b, value = b });
            return Json(output);
        }

        [HttpPost]
        public ActionResult LoadCase(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return PartialView("_Case", _caseService.GetById(id));
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_caseService.GetAll());
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var caseEntity =
            _caseService.GetById(id);
            return View(caseEntity);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Case());
        }

        [HttpPost]
        public ActionResult Create(Case component, string motherboardCompatibility)
        {
            if (ModelState.IsValid && !string.IsNullOrEmpty(motherboardCompatibility))
            {
                component.MotherboardCompatibility =
                    motherboardCompatibility.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                        .Select(s => s.Trim())
                        .ToList();
                _caseService.Insert(component);
                return RedirectToAction("Index");
            }
            return View(component);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _caseService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var caseEntity =
            _caseService.GetById(id);
            return View(caseEntity);
        }

        [HttpPost]
        public ActionResult Edit(Case component, string motherboardCompatibility)
        {
            if (ModelState.IsValid && !string.IsNullOrEmpty(motherboardCompatibility))
            {
                component.MotherboardCompatibility =
                    motherboardCompatibility.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                        .Select(s => s.Trim())
                        .ToList();
                _caseService.Update(component);
                return RedirectToAction("Index");
            }
            return View(component);
        }
    }
}

PcConfigurator/Views/Case/Create.cshtml
@model PcConfigurator.Entities.Case

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Case</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Motherboard Compatibility", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("motherboardCompatibility", "", new { @class = "form-control" })
                <span id="helpBlock1" class="help-block">Separate with coma</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Case/Details.cshtml
@model PcConfigurator.Entities.Case

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Case</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotherboardCompatibility)
        </dt>

        <dd>
            @string.Join(", ", Model.MotherboardCompatibility)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PcConfigurator/Views/Case/Edit.cshtml
@model PcConfigurator.Entities.Case

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Case</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Motherboard Compatibility", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("motherboardCompatibility", string.Join(", ", Model.MotherboardCompatibility), new { @class = "form-control" })
                <span id="helpBlock1" class="help-block">Separate with coma</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Case/Index.cshtml
@model IEnumerable<PcConfigurator.Entities.Case>

@{
    ViewBag.Title = "Cases";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Case</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MotherboardCompatibility)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @string.Join(", ", item.MotherboardCompatibility)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

PcConfigurator/Views/Case/_Case.cshtml
@model PcConfigurator.Entities.Case
<hr />
<div class="row vcenter">
    <div class="col-xs-10 col-md-5">
        <div class="panel panel-success">
            <div class="panel-heading">@this.Model.Brand @this.Model.Name</div>
            <table class="table table-hover">
                <tr>
                    <td>@Html.DisplayNameFor(model => model.MotherboardCompatibility)</td>
                    <td>@Html.DisplayFor(model => model.MotherboardCompatibility)</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-xs-2 col-md-1">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    </div>
</div>

PcConfigurator/Views/Case/_DropdownListGroup.cshtml
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("CaseBrand", Enumerable.Empty<SelectListItem>(), "Brand", new { @class = "form-control", @data_url = @Url.Action("LoadCaseId", "Case") })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("CaseId", Enumerable.Empty<SelectListItem>(), "Model", new { @class = "form-control", @data_url = @Url.Action("LoadCase", "Case"), @style = "display:none;" })
            </div>
        </div>
    </div>
</div>
<div id="CaseView"></div>