PcConfigurator/Entities/Mongo/Psu.cs
using MongoDB.Bson.Serialization.Attributes;

namespace PcConfigurator.Entities.Mongo
{
    public class Psu : MongoEntity
    {
        [BsonElement("brand")]
        [BsonRequired]
        public string Brand { get; set; }

        [BsonElement("model")]
        [BsonRequired]
        public string Model { get; set; }

        [BsonElement("type")]
        [BsonRequired]
        public string Type { get; set; }

        [BsonElement("power")]
        [BsonRequired]
        public string MaximumPower { get; set; }

        [BsonElement("efficiency")]
        [BsonRequired]
        public string Efficiency { get; set; }

        [BsonElement("features")]
        public string Features { get; set; }
    }
}

PcConfigurator/Entities/Psu.cs
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace PcConfigurator.Entities
{
    public class Psu : Component
    {
        [Required]
        public int MaximumPower { get; set; }
        [Required]
        public int Efficiency { get; set; }
        public int ActualPower { get; set; }
    }
}

PcConfigurator/Controllers/PsuController.cs
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Newtonsoft.Json;
using PcConfigurator.Entities;
using PcConfigurator.Models.HomeModels;
using PcConfigurator.Service;

namespace PcConfigurator.Controllers
{
    public class PsuController : Controller
    {
        private readonly IPsuService _psuService;

        public PsuController(IPsuService psuService)
        {
            _psuService = psuService;
        }

        [HttpPost]
        public ActionResult LoadPsuBrand(ConfigurationFormModel model)
        {
            var powerConsumption = model.MemoryPowerConsumption + model.MotherboardPowerConsumption +
                                   model.CpuPowerConsumption + model.StoragePowerConsumption + model.GpuPowerConsumption;
            var output = _psuService.GetPsuBrandsByPowerConsumption(powerConsumption).Select(s => new { text = s, value = s });
            return Json(output);
        }

        [HttpPost]
        public ActionResult LoadPsuId(ConfigurationFormModel model)
        {
            var output = _psuService.GetPsusByConfiguration(model).Select(p => new { text = p.Name, value = p.Id });
            return Json(output);
        }

        [HttpPost]
        public ActionResult LoadPsu(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return PartialView("_Psu", _psuService.GetById(id));
        }


        [HttpGet]
        public ActionResult Index()
        {
            return View(_psuService.GetAll());
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_psuService.GetById(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Psu());
        }

        [HttpPost]
        public ActionResult Create(Psu component)
        {
            if (ModelState.IsValid)
            {
                _psuService.Insert(component);
                return RedirectToAction("Index");
            }
            return View(component);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _psuService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_psuService.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Psu component)
        {
            if (ModelState.IsValid)
            {
                _psuService.Update(component);
                return RedirectToAction("Index");
            }
            return View(component);
        }
    }
}

PcConfigurator/Views/Psu/Create.cshtml
@model PcConfigurator.Entities.Psu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Psu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaximumPower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaximumPower, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaximumPower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Efficiency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Efficiency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Efficiency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Psu/Details.cshtml
@model PcConfigurator.Entities.Psu

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Psu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaximumPower)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaximumPower)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Efficiency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Efficiency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualPower)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualPower)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PcConfigurator/Views/Psu/Edit.cshtml
@model PcConfigurator.Entities.Psu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Psu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaximumPower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaximumPower, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaximumPower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Efficiency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Efficiency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Efficiency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PcConfigurator/Views/Psu/Index.cshtml
@model IEnumerable<PcConfigurator.Entities.Psu>

@{
    ViewBag.Title = "Psus";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Psu</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaximumPower)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Efficiency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActualPower)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaximumPower)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Efficiency)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActualPower)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

PcConfigurator/Views/Psu/_DropdownListGroup.cshtml
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("PsuBrand", Enumerable.Empty<SelectListItem>(), "Brand", new { @class = "form-control", @data_url = @Url.Action("LoadPsuId", "Psu") })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                @Html.DropDownList("PsuId", Enumerable.Empty<SelectListItem>(), "Model", new { @class = "form-control", @data_url = @Url.Action("LoadPsu", "Psu"), @style = "display:none;" })
            </div>
        </div>
    </div>
</div>
<div id="PsuView"></div>

PcConfigurator/Views/Psu/_Psu.cshtml
@model PcConfigurator.Entities.Psu
<hr />
<div class="row vcenter">
    <div class="col-xs-10 col-md-5">
        <div class="panel panel-success">
            <div class="panel-heading">@this.Model.Brand @this.Model.Name</div>
            <table class="table table-hover">
                <tr>
                    <td>@Html.DisplayNameFor(model => model.MaximumPower)</td>
                    <td>@Html.DisplayFor(model => model.MaximumPower)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Efficiency)</td>
                    <td>@Html.DisplayFor(model => model.Efficiency)</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-xs-2 col-md-1">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    </div>
</div>